### ISSUE TITLE
Polish Link Checker for use on wm.org

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/wcc-contentful#87]
- [x] update the underlying package (the PR that's started)
- [ ] make updates to script to support wm.org

**Comment by gburgett** [comment]
wm.org as a billboard site currently doesn't need anything other than the basic link checking functionality.  As it stands none of the wrapper code in watermarkresources would be super useful, because it's too tightly tied to WMR.

At the time that it needs custom HTML parsing to check all the links, we can port over more of the code from watermarkresources.
